name: Stage Deploy

concurrency: deploy-lock

on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'
      - 'staging'
      - 'prod'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy not for real
      run: echo "Deploy something ..."
