name: Merge PRs with rebase
on:
  pull_request_review_comment:
    types: [created]
jobs:
  merge:
    name: Merge
    if: contains(github.event.comment.body, '/clean-merge')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: Automatic Rebase
        shell: bash
        run: |
          set -e

          PR_NUMBER=$(jq -r ".pull_request.number" "$GITHUB_EVENT_PATH")
          if [[ "$PR_NUMBER" == "null" ]]; then
            echo "Failed to determine PR Number."
            exit 1
          fi

          echo "Collecting information about PR #$PR_NUMBER of $GITHUB_REPOSITORY..."

          BASE_BRANCH=$(jq -r ".pull_request.base.ref" "$GITHUB_EVENT_PATH")

          if [[ -z "$BASE_BRANCH" ]]; then
            echo "Cannot get base branch information for PR #$PR_NUMBER!"
            exit 1
          fi
          echo "Base branch for PR #$PR_NUMBER is $BASE_BRANCH"

          HEAD_BRANCH=$(jq -r ".pull_request.head.ref" "$GITHUB_EVENT_PATH")
          if [[ -z "$HEAD_BRANCH" ]]; then
            echo "Cannot get head branch information for PR #$PR_NUMBER!"
            exit 1
          fi

          set -o xtrace

          # make sure branches are up-to-date
          git fetch origin $BASE_BRANCH
          git fetch origin $HEAD_BRANCH

          # do the merge with rebase
          git checkout $BASE_BRANCH
          git pull --rebase origin $HEAD_BRANCH

          # push back
          git push --force-with-lease